export function getPenjelasan(label) {
  const jelas = {
    Healthy: "Kelas 'healthy' menunjukkan tanaman tomat yang bebas dari tanda-tanda penyakit atau serangan hama yang signifikan. Daun berwarna hijau segar tanpa bercak, layu, atau perubahan warna yang tidak normal. Batang terlihat kokoh dan tidak menunjukkan lesi atau kerusakan. Pertumbuhan tanaman terlihat vigor dan sesuai dengan fase perkembangannya. Buah berkembang normal tanpa adanya cacat, busuk, atau gejala penyakit lainnya. Sistem perakaran juga sehat dan mampu menyerap nutrisi dengan baik. Tanaman yang sehat memiliki potensi hasil panen yang optimal dan lebih tahan terhadap tekanan lingkungan dan serangan organisme pengganggu.",
    Late_blight: "Late blight adalah penyakit jamur yang sangat merusak dan dapat menyebar dengan cepat dalam kondisi lembab dan sejuk. Gejala awal berupa bercak-bercak hijau pucat hingga cokelat keabu-abuan yang tidak beraturan pada daun, seringkali dimulai dari tepi daun. Pada kondisi lembab, lapisan putih seperti tepung dapat terlihat di bagian bawah daun. Batang dan buah juga dapat terinfeksi, menunjukkan bercak cokelat kehitaman yang tegas. Penyakit ini dapat menyebabkan kerusakan parah pada seluruh tanaman dalam waktu singkat jika tidak dikendalikan. Kelembaban tinggi dan suhu antara 18-22°C sangat mendukung perkembangan jamur ini.",
    Early_blight: "Early blight adalah penyakit jamur umum pada tomat yang ditandai dengan munculnya bercak-bercak cokelat hingga hitam berbentuk bulat atau oval dengan lingkaran konsentris yang khas seperti target. Bercak ini umumnya dimulai pada daun bagian bawah dan dapat meluas ke atas. Pada kondisi lembab, bercak dapat membesar dan menyebabkan daun menguning, kering, dan akhirnya gugur. Infeksi parah dapat menyebabkan defoliasi yang signifikan, melemahkan tanaman, dan mengurangi hasil buah. Jamur ini dapat bertahan pada sisa-sisa tanaman di tanah dan menyebar melalui angin dan percikan air.",
    Bacterial_spot: "Bacterial spot adalah penyakit bakteri yang menyerang daun, batang, dan buah tomat. Pada daun, gejala awal berupa bercak-bercak kecil berwarna hijau tua yang kemudian menjadi cokelat dan bertepian menguning. Bercak seringkali terlihat berair dan dapat bersatu membentuk bercak yang lebih besar dan tidak beraturan. Pada buah, muncul bercak-bercak kecil, dangkal, sedikit menonjol, dan kasar berwarna cokelat hingga hitam dengan halo berminyak. Penyakit ini menyebar melalui percikan air hujan, irigasi, dan kontak mekanis. Kondisi hangat dan lembab sangat mendukung perkembangan bakteri ini.",
    Septoria_leaf_spot: "Septoria leaf spot adalah penyakit jamur yang ditandai dengan munculnya bercak-bercak kecil berbentuk bulat dengan pusat berwarna abu-abu atau cokelat muda dan tepi berwarna cokelat tua. Di tengah bercak sering terlihat bintik-bintik hitam kecil yang merupakan badan buah jamur (pycnidia). Penyakit ini umumnya menyerang daun bagian bawah terlebih dahulu dan dapat menyebar ke daun bagian atas. Infeksi parah dapat menyebabkan daun menguning, kering, dan gugur, mengurangi kemampuan fotosintesis tanaman dan berdampak pada hasil buah. Kelembaban tinggi dan suhu hangat mendukung perkembangan penyakit ini.",
    Tomato_yellow_leaf_curl_virus: "Tomato Yellow Leaf Curl Virus (TYLCV) adalah penyakit virus yang sangat merusak pada tanaman tomat, terutama di daerah tropis dan subtropis. Gejala khasnya adalah daun-daun muda yang mengeriting ke atas, menebal, dan berwarna kuning. Pertumbuhan tanaman menjadi kerdil dan terhambat, dengan ruas batang yang memendek. Pembentukan bunga dan buah juga terganggu, dan buah yang terbentuk biasanya kecil dan sedikit. Virus ini ditularkan oleh kutu kebul (Bemisia tabaci) secara persisten, artinya virus akan terus berada di dalam tubuh kutu kebul selama hidupnya setelah mendapatkan virus dari tanaman yang terinfeksi.",
    Tomato_mosaic_virus: "Tomato Mosaic Virus (ToMV) adalah virus yang menyebabkan berbagai gejala pada tanaman tomat, termasuk pola mosaik berwarna hijau muda dan hijau tua pada daun, daun mengeriting atau melintir, pertumbuhan tanaman terhambat, dan penurunan hasil buah. Buah yang terbentuk mungkin kecil, tidak rata, dan memiliki bercak-bercak kuning atau cokelat. Virus ini sangat menular dan dapat bertahan lama pada benih, sisa-sisa tanaman, dan bahkan pada permukaan alat-alat pertanian. Penularan dapat terjadi melalui kontak mekanis, seperti saat pemangkasan atau penjarangan, dan melalui benih yang terinfeksi.",
    Target_spot: "Target spot adalah penyakit jamur yang ditandai dengan bercak-bercak pada daun yang menyerupai target, dengan lingkaran konsentris berwarna cokelat muda hingga cokelat tua dan pusat yang lebih terang. Bercak ini biasanya berukuran lebih besar dari bercak akibat early blight dan tidak memiliki tepi yang jelas. Pada kondisi lembab, spora jamur dapat terlihat sebagai lapisan tipis berwarna putih atau abu-abu di bagian bawah bercak. Infeksi parah dapat menyebabkan daun menguning, kering, dan gugur. Jamur ini dapat bertahan pada sisa-sisa tanaman dan gulma, serta menyebar melalui angin dan percikan air.",
    Leaf_Mold: "Leaf mold adalah penyakit jamur yang umumnya menyerang tanaman tomat yang ditanam di rumah kaca atau kondisi lembab dengan sirkulasi udara yang buruk. Gejala awal berupa bercak-bercak kuning pucat pada permukaan atas daun, yang kemudian berkembang menjadi lapisan beludru berwarna cokelat kehijauan atau ungu pada permukaan bawah daun. Infeksi parah dapat menyebabkan daun menguning, kering, dan gugur dari bawah ke atas. Kelembaban tinggi dan suhu antara 20-24°C sangat mendukung perkembangan jamur ini.",
    Spider_mites : " Tungau laba-laba (terutama Tetranychus urticae atau two-spotted spider mite) adalah hama kecil yang menghisap cairan sel tanaman, menyebabkan bercak-bercak kecil berwarna kuning atau perak pada permukaan atas daun. Serangan parah dapat menyebabkan daun menguning seluruhnya, mengering, dan gugur. Hama ini juga menghasilkan jaring-jaring halus di bagian bawah daun dan di antara daun dan batang. Tungau berkembang biak dengan cepat dalam kondisi kering dan hangat, dan populasinya dapat meningkat pesat dalam waktu singkat.",
    Powdery_mildew : "Powdery mildew adalah penyakit jamur yang mudah dikenali dengan adanya lapisan tepung berwarna putih atau abu-abu pada permukaan atas daun, batang, dan kadang-kadang buah. Gejala awal berupa bercak-bercak kecil berwarna putih yang kemudian meluas dan menutupi seluruh permukaan daun. Meskipun jarang menyebabkan kematian tanaman, infeksi parah dapat menghambat pertumbuhan, menyebabkan daun menguning dan gugur, serta mengurangi kualitas dan hasil buah. Kondisi kering dengan kelembaban malam yang tinggi dan sirkulasi udara yang buruk mendukung perkembangan jamur ini."
  };

  return jelas[label] || "Belum ada Penjelesan";
}