export function getRekomendasi(label) {
  const solusi = {
    Healthy: "Mempertahankan kesehatan tanaman tomat memerlukan praktik budidaya yang baik. Pastikan tanah memiliki drainase yang baik dan kaya akan nutrisi. Berikan pupuk yang seimbang sesuai dengan kebutuhan tanaman. Lakukan penyiraman secara teratur dan hindari kelembaban berlebihan pada daun. Jaga kebersihan kebun dari gulma dan sisa-sisa tanaman yang sakit. Lakukan pemantauan rutin terhadap keberadaan hama dan penyakit sejak dini. Gunakan benih dan bibit yang berkualitas dan tahan terhadap penyakit umum. Praktik rotasi tanaman juga membantu menjaga kesehatan tanah dan mengurangi risiko penumpukan patogen.",
    Late_blight: "Pengendalian late blight memerlukan pendekatan terpadu. Hindari menanam tomat terlalu rapat untuk meningkatkan sirkulasi udara. Gunakan benih dan bibit yang sehat dan bersertifikat. Lakukan penyiraman di pagi hari agar daun cepat kering. Jika gejala awal muncul, segera buang dan musnahkan bagian tanaman yang terinfeksi. Aplikasi fungisida protektif berbahan aktif mankozeb atau klorotalonil sebelum muncul gejala dapat membantu mencegah infeksi. Jika infeksi sudah menyebar, gunakan fungisida sistemik berbahan aktif seperti metalaksil atau dimetomorf sesuai dosis dan interval yang dianjurkan. Rotasi tanaman dengan tanaman non-solanaceae juga penting untuk mengurangi inokulum jamur di tanah.",
    Early_blight: "Pengendalian early blight dimulai dengan praktik sanitasi kebun yang baik, yaitu membersihkan sisa-sisa tanaman yang terinfeksi setelah panen. Hindari menanam tomat terlalu rapat untuk meningkatkan sirkulasi udara. Lakukan penyiraman di pangkal batang untuk menghindari kelembaban berlebihan pada daun. Aplikasi fungisida protektif berbahan aktif mankozeb atau klorotalonil secara teratur, terutama saat kondisi lingkungan mendukung perkembangan penyakit. Jika gejala sudah muncul, gunakan fungisida sistemik atau kontak yang efektif terhadap *Alternaria solani*, seperti azoksistrobin atau difenokonazol, sesuai dosis dan interval yang dianjurkan. Rotasi tanaman dengan tanaman non-solanaceae juga dapat membantu mengurangi inokulum jamur di tanah.",
    Bacterial_spot: " Pengendalian bacterial spot meliputi penggunaan benih yang sehat dan bebas penyakit. Hindari penyiraman dari atas dan usahakan agar daun tetap kering. Jaga kebersihan kebun dari sisa-sisa tanaman yang terinfeksi. Jika gejala awal muncul, segera buang bagian tanaman yang sakit. Aplikasi bakterisida berbahan aktif tembaga oksiklorida atau streptomisin dapat membantu mengendalikan penyebaran penyakit, namun efektivitasnya terbatas setelah infeksi menyebar luas. Hindari bekerja di kebun saat daun masih basah untuk mencegah penyebaran bakteri secara mekanis. Rotasi tanaman minimal dua tahun dengan tanaman non-solanaceae juga penting.",
    Septoria_leaf_spot: "Pengendalian septoria leaf spot meliputi praktik sanitasi kebun dengan membuang dan memusnahkan daun-daun yang terinfeksi. Hindari penyiraman dari atas yang dapat membasahi daun dan memicu penyebaran spora jamur. Tingkatkan sirkulasi udara di sekitar tanaman dengan memberikan jarak tanam yang cukup dan melakukan pemangkasan daun bagian bawah yang dekat dengan tanah. Aplikasi fungisida protektif berbahan aktif mankozeb atau klorotalonil dapat membantu mencegah infeksi. Jika penyakit sudah menyebar, gunakan fungisida sistemik seperti azoksistrobin atau propikonazol sesuai dosis dan interval yang dianjurkan. Rotasi tanaman minimal dua tahun dengan tanaman non-solanaceae juga disarankan.",
    Tomato_yellow_leaf_curl_virus: "Pengendalian TYLCV terutama berfokus pada pengendalian vektor kutu kebul. Gunakan insektisida sistemik seperti imidakloprid atau tiametoksam untuk mengurangi populasi kutu kebul. Aplikasi insektisida harus dilakukan secara teratur dan bergilir dengan bahan aktif yang berbeda untuk mencegah resistensi. Gunakan mulsa plastik berwarna perak untuk memantulkan cahaya dan mengganggu orientasi kutu kebul. Pasang perangkap kuning lengket untuk memantau populasi kutu kebul. Cabut dan musnahkan tanaman yang terinfeksi TYLCV sesegera mungkin untuk mencegah penyebaran virus. Gunakan bibit yang sehat dan bebas virus, serta pertimbangkan penggunaan varietas tomat yang tahan atau toleran terhadap TYLCV jika tersedia.",
    Tomato_mosaic_virus: " Tidak ada penyembuhan untuk tanaman yang sudah terinfeksi ToMV. Langkah-langkah pengendalian berfokus pada pencegahan penyebaran virus. Gunakan benih yang bersertifikat bebas virus. Lakukan sanitasi yang ketat dengan mencuci tangan dan alat-alat pertanian dengan sabun atau disinfektan sebelum dan sesudah menangani tanaman. Cabut dan musnahkan tanaman yang menunjukkan gejala ToMV sesegera mungkin. Hindari menanam tomat berdekatan dengan tanaman lain yang rentan terhadap virus yang sama, seperti tembakau dan paprika. Pengendalian hama vektor seperti kutu daun juga penting karena dapat membantu penyebaran virus.",
    Target_spot: " Pengendalian target spot melibatkan praktik sanitasi kebun dengan membersihkan sisa-sisa tanaman dan gulma yang dapat menjadi sumber inokulum. Hindari penyiraman dari atas dan tingkatkan sirkulasi udara di sekitar tanaman. Aplikasi fungisida protektif berbahan aktif mankozeb atau klorotalonil dapat membantu mencegah infeksi. Jika gejala sudah muncul, gunakan fungisida sistemik seperti difenokonazol atau propikonazol sesuai dosis dan interval yang dianjurkan. Pastikan penyemprotan merata, terutama pada bagian bawah daun. Rotasi tanaman dengan tanaman non-solanaceae juga dapat membantu mengurangi risiko penyakit.",
    Leaf_Mold: "Pengendalian leaf mold terutama berfokus pada pengelolaan lingkungan. Tingkatkan sirkulasi udara di sekitar tanaman dengan memberikan jarak tanam yang cukup dan memastikan ventilasi yang baik di rumah kaca. Kurangi kelembaban dengan menghindari penyiraman dari atas dan menyiram di pagi hari agar daun cepat kering. Buang dan musnahkan daun-daun yang terinfeksi sesegera mungkin. Aplikasi fungisida protektif berbahan aktif mankozeb atau klorotalonil dapat membantu mencegah infeksi. Jika penyakit sudah menyebar, gunakan fungisida sistemik seperti trifloksistrobin atau boskalid sesuai dosis dan interval yang dianjurkan.",
    Spider_mites : "Pengendalian leaf mold terutama berfokus pada pengelolaan lingkungan. Tingkatkan sirkulasi udara di sekitar tanaman dengan memberikan jarak tanam yang cukup dan memastikan ventilasi yang baik di rumah kaca. Kurangi kelembaban dengan menghindari penyiraman dari atas dan menyiram di pagi hari agar daun cepat kering. Buang dan musnahkan daun-daun yang terinfeksi sesegera mungkin. Aplikasi fungisida protektif berbahan aktif mankozeb atau klorotalonil dapat membantu mencegah infeksi. Jika penyakit sudah menyebar, gunakan fungisida sistemik seperti trifloksistrobin atau boskalid sesuai dosis dan interval yang dianjurkan.",
    Powdery_mildew : "Pengendalian powdery mildew meliputi peningkatan sirkulasi udara di sekitar tanaman dengan memberikan jarak tanam yang cukup dan melakukan pemangkasan daun bagian bawah. Hindari pemupukan nitrogen berlebihan yang dapat memicu pertumbuhan tunas muda yang rentan. Aplikasi fungisida protektif berbahan aktif belerang atau trifloksistrobin dapat membantu mencegah dan mengendalikan penyakit. Jika infeksi sudah menyebar, gunakan fungisida sistemik seperti miklobutanil atau difenokonazol sesuai dosis dan interval yang dianjurkan. Aplikasi harus merata pada seluruh bagian tanaman yang terinfeksi. Penggunaan varietas tomat yang tahan terhadap powdery mildew juga merupakan pilihan yang baik jika tersedia."
  };

  return solusi[label] || "Belum ada rekomendasi untuk label ini.";
}
